beartrail:
  application:
    name: market-data
    
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

  # Upstox API Configuration
  upstox:
    auth-token: ${UPSTOX_AUTH_TOKEN:eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIzNENWRzUiLCJqdGkiOiI2ODkxYzNkZTY0NWM2MzQxYjAzYTY1MzkiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc1NDM4MzMyNiwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzU0NDMxMjAwfQ.FueG_zhibzZG6AaBg4KVPFJGRGQ-hVNRYK8irWuq35Q}
    base-url: ${UPSTOX_API_URL:https://api.upstox.com/v3}

  kafka:
    topics:
      market-data-updates: market-data-updates

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: market-data-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      market-data-updates: market-data-updates
  datasource:
    url: jdbc:postgresql://localhost:5432/market_data
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true