version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tradersim-postgres
    environment:
      POSTGRES_DB: tradersim
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tradersim-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tradersim"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: tradersim-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tradersim-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  tradersim-network:
    driver: bridge
