name: Dependency Review

on:
  pull_request:
    branches: [ main ]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
